### ISSUE TITLE
Don't crash when Python doesn't have ctypes installed

### ISSUE THREAD

**Issue by pinkwah** [equinor/komodoenv#31]
We use ctypes to test whether the user is on NFS or not via a Linux-only function: https://github.com/equinor/komodoenv/blob/master/komodoenv/statfs.py

This is just a nice feature for the user, and we shouldn't crash if the user is missing the ctypes module (which can happen on particularly thin Python installs)

**Comment by JensGM** [comment]
ctypes is part of python and is usually present. It is an optional module, but it is present in the redhat builtin python distribution. So I think the issue here is related to the cloning of python rather than ctypes missing

**Comment by dotfloat** [comment]
It's still a nice polishing opportunity. `ctypes` is an optional component, but so is the functionality we're using it for.

**Comment by xjules** [comment]
Is this issue still relevant @pinkwah ?
