### ISSUE TITLE
`komodoenv` assumes `subprocess` `/bin/bash` only prints output from command

### ISSUE THREAD

**Issue by anders-kiaer** [equinor/komodoenv#36]
I have one line printed when a new terminal is started, resulting in the `assert` statement on line 71 https://github.com/equinor/komodoenv/blob/45d0ccd26c9d6f81c3503ec52e5c3a8931527c95/komodoenv/__main__.py#L59-L71 failing (`3 !== 2`).

Could one easy fix be to relax it to `>= 2` and then use the last two output lines (i.e. effectively ignoring any start-up messages the user has in `bash`)?

**Comment by dotfloat** [comment]
What are you printing? Perhaps it should only be printed when bash is run in interactive mode?

**Comment by jondequinor** [comment]
And how are you printing?

**Comment by anders-kiaer** [comment]
Printing "indirectly" by sourcing `/prog/sdpsoft/` (which gives a printed line at source time it seems).

**Comment by jondequinor** [comment]
In `.bashrc` I assume? You should move that to `.bash_profile`. Either way, I think a fix here would be to provide a non-printing rc script through `--rcfile` if that mitigates this.

**Comment by jondequinor** [comment]
What does `BASH_ENV= bash -c "echo foo"` print? Compare it to `bash -c "echo foo"`.

**Comment by anders-kiaer** [comment]
The former gives no line, the latter prints the same line (and moving the `source` command to `.bash_profile` gives no printed line for both commands 👍).

**Comment by dotfloat** [comment]
The PR might not be a bulletproof fix. If this issue occurs again, feel free to reopen.
