### ISSUE TITLE
Should "out-of-date" komodoenv result in exit code 1?

### ISSUE THREAD

**Issue by lars-petter-hauge** [equinor/komodoenv#46]
Given that your komodoenv becomes outdated, the sourcing will result in a `sys.exit` with a message letting you know you should update.

https://github.com/equinor/komodoenv/blob/b35f7824d8ebbe1c31c9b7d03af64a0fc32c0ee0/komodoenv/update.py#L412

Should this be an exit code of `1`?

Use case where this can be challenging: running this as part of ERT will make the forward model job fail even before status's are reported back.

**Comment by pinkwah** [comment]
Yeah, it doesn't make sense to exit with code `1`. We can instead `print(..., file=sys.stderr)` and `sys.exit(0)`.
