### ISSUE TITLE
Pytest fails when filterwarnings are present in configuration

### ISSUE THREAD

**Issue by oyvindeide** [equinor/komodoenv#8]
Tested with komodo version `2020.08.00-py36`, steps to reproduce:

Create a minimal test, `test_minimal.py`:
```
import pandas

def test_something_simple():
    pass
```

Create `pytest.ini`:
```
[pytest]
filterwarnings =
    error
```
Fails with:

`RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject`

**Comment by dotfloat** [comment]
It seems that this is a numpy version issue that is most likely resolved or resolvable. Reopen if this is still an issue.
